# Generated by Django 5.1.7 on 2025-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('importance', models.BooleanField(choices=[(False, 'Срочное'), (True, 'Не обязательное')], default=1)),
                ('StatusTask', models.BooleanField(choices=[(False, 'Выполняется'), (True, 'Завершено')], default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_running', models.DateField(auto_now=True)),
                ('time_finish', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
