# Generated by Django 5.1.7 on 2025-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_running',
            field=models.DateField(),
        ),
    ]
